---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/v1/aeroplanes":
    get:
      summary: list aeroplanes
      responses:
        '200':
          description: successful
    post:
      summary: create aeroplane
      responses:
        '200':
          description: successful
  "/api/v1/aeroplanes/{id}":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    get:
      summary: show aeroplane
      responses:
        '200':
          description: successful
    patch:
      summary: update aeroplane
      responses:
        '200':
          description: successful
    put:
      summary: update aeroplane
      responses:
        '200':
          description: successful
    delete:
      summary: delete aeroplane
      responses:
        '200':
          description: successful
servers:
- url: https://{defaultHost}
  variables:
    defaultHost:
      default: www.example.com
